// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fueuqfwkpspeekxtuwre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1ZXVxZndrcHNwZWVreHR1d3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzk0NTcsImV4cCI6MjA1OTk1NTQ1N30.zKm1k3BPkodDNpW35w8rE9U9JBZQGHFobY-M2kYW90o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);